# Generated by Django 3.0.5 on 2020-05-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_category_todos_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='todos_count',
        ),
    ]
