# Generated by Django 3.0.5 on 2020-05-03 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_auto_20200503_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'verbose_name': 'Задачу', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='todos_count',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='todos_count',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='slug',
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('High Priority', 'Высокий приоритет'), ('Medium Priority', 'Средний приоритет'), ('Low Priority', 'Низкий приоритет')], default='Medium Priority', max_length=128),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='category',
            field=models.ManyToManyField(blank=True, to='tasks.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Priority', verbose_name='Приоритет'),
        ),
    ]
